# SSL Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  secretName: harbor-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - registry.dev01.internal.minipig.org


---
# Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-ingress
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`registry.dev01.internal.minipig.org`) || Host(`registry.minipig.org`)
    priority: 1
    services:
      - kind: Service
        name: harbor
        port: 80
  tls:
    secretName: harbor-cert